name: env_geo
channels:
  - conda-forge
  - apple
dependencies:
  - anyio=4.0.0=pyhd8ed1ab_0
  - aom=3.6.1=hb765f3a_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311heffc1b2_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.7.4=h2ed40ff_1
  - aws-c-cal=0.6.2=h12c43c8_2
  - aws-c-common=0.9.3=hb547adb_0
  - aws-c-compression=0.2.17=h12c43c8_3
  - aws-c-event-stream=0.3.2=h88fe898_1
  - aws-c-http=0.7.13=he062130_1
  - aws-c-io=0.13.32=h13ba428_4
  - aws-c-mqtt=0.9.6=h3ffe4bb_2
  - aws-c-s3=0.3.17=hf064be9_3
  - aws-c-sdkutils=0.1.12=h12c43c8_2
  - aws-checksums=0.1.17=h12c43c8_2
  - aws-crt-cpp=0.23.1=h96fc18d_5
  - aws-sdk-cpp=1.11.156=he831950_3
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.6.3=pyhd8ed1ab_0
  - blosc=1.21.5=hc338f07_0
  - bokeh=3.2.2=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h00df5ed_4
  - boto3=1.28.71=pyhd8ed1ab_0
  - botocore=1.31.72=pyhd8ed1ab_0
  - branca=0.6.0=pyhd8ed1ab_0
  - bravado=11.0.3=pyhd8ed1ab_0
  - bravado-core=5.17.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.19.1=hb547adb_0
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=hc5b65c1_1017
  - cartopy=0.22.0=py311h9e438b8_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.16.0=py311h4a08483_0
  - cfitsio=4.3.0=hca87796_0
  - cftime=1.6.2=py311hb49d859_2
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.0.1=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.1.1=py311he4fd1f5_1
  - cryptography=41.0.5=py311h71175c2_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dask-core=2023.9.3=pyhd8ed1ab_0
  - datashader=0.15.2=pyhd8ed1ab_0
  - datashape=0.5.4=py_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.0=py311ha891d26_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - ffmpeg=6.0.0=gpl_h1ceb99f_105
  - fiona=1.9.4=py311h0e2296b_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.43.0=py311heffc1b2_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - freexl=2.0.0=hfbad9fb_0
  - fribidi=1.0.10=h27ca646_0
  - fsspec=2023.9.2=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdal=3.7.2=py311h354944d_4
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.13.2=pyhd8ed1ab_1
  - geopandas-base=0.13.2=pyha770c72_1
  - geopy=2.4.0=pyhd8ed1ab_0
  - geos=3.12.0=h13dd4ca_0
  - geotiff=1.7.1=h94e20d0_13
  - geoviews=1.10.1=pyhd8ed1ab_0
  - geoviews-core=1.10.1=pyha770c72_0
  - gettext=0.21.1=h0186832_0
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h1a8c8d9_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glog=0.6.0=h6da1cb0_0
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - graphite2=1.3.13=h9f76cd9_1001
  - harfbuzz=8.2.1=hf1a6348_0
  - hdf4=4.2.15=h8111dcc_6
  - hdf5=1.14.2=nompi_h3aba7b3_100
  - holoviews=1.17.1=pyhd8ed1ab_0
  - hvplot=0.8.4=pyhd8ed1ab_1
  - icu=73.2=hc8870d7_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - ipykernel=6.25.2=pyh1050b4e_0
  - ipython=8.16.0=pyh31c8845_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jasper=4.0.0=hff9eb24_1
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - json-c=0.17=h40ed0f5_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h267d04e_3
  - jsonref=0.2=py_0
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format=4.19.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py311h267d04e_9
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter-resource-usage=1.0.1=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py311h267d04e_0
  - jupyter_events=0.7.0=pyhd8ed1ab_2
  - jupyter_server=2.7.3=pyhd8ed1ab_1
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.25.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - kealib=1.5.2=h47b5e36_1
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - krb5=1.21.2=h92f50d5_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.15=h40e5a24_2
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.1=h13dd4ca_0
  - libarchive=3.7.2=h82b9b87_0
  - libarrow=13.0.0=h0c25ffe_4_cpu
  - libass=0.17.1=hf7da4fe_1
  - libblas=3.9.0=18_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=18_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.3.0=hc52a3a8_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.12=h2757513_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.7.2=hcae775b_4
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libglib=2.78.0=h24e9cb9_0
  - libgoogle-cloud=2.12.0=hde42cda_2
  - libgrpc=1.57.0=hdbe17d8_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - libjpeg-turbo=2.1.5.1=hb547adb_1
  - libkml=1.3.0=h41464e4_1015
  - liblapack=3.9.0=18_osxarm64_openblas
  - liblapacke=3.9.0=18_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - libnetcdf=4.9.2=nompi_hb2fb864_112
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.24=openmp_hd76b1f2_0
  - libopencv=4.8.1=py311h59bfeaa_0
  - libopenvino=2023.1.0=h13dd4ca_0
  - libopenvino-arm-cpu-plugin=2023.1.0=h13dd4ca_0
  - libopenvino-auto-batch-plugin=2023.1.0=h13dd4ca_0
  - libopenvino-auto-plugin=2023.1.0=h13dd4ca_0
  - libopenvino-hetero-plugin=2023.1.0=h13dd4ca_0
  - libopenvino-ir-frontend=2023.1.0=h13dd4ca_0
  - libopenvino-onnx-frontend=2023.1.0=h13dd4ca_0
  - libopenvino-paddle-frontend=2023.1.0=h13dd4ca_0
  - libopenvino-pytorch-frontend=2023.1.0=h13dd4ca_0
  - libopenvino-tensorflow-frontend=2023.1.0=h13dd4ca_0
  - libopenvino-tensorflow-lite-frontend=2023.1.0=h13dd4ca_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h76d750c_0
  - libpq=16.0=hcea71ed_1
  - libprotobuf=4.23.4=hf590ac1_6
  - librttopo=1.1.0=h667cd51_14
  - libsodium=1.0.18=h27ca646_1
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.1.0=h32510b6_0
  - libsqlite=3.43.0=hb31c410_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=h77c4dce_1
  - libunistring=0.9.10=h3422bc3_0
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libvpx=1.13.1=hb765f3a_0
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.11.5=h25269f3_1
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.2.13=h53f4e23_5
  - linkify-it-py=2.0.0=pyhd8ed1ab_0
  - llvm-openmp=16.0.6=h1c12783_0
  - llvmlite=0.40.1=py311hea943cd_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h642e427_1000
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markdown=3.4.4=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311heffc1b2_1
  - matplotlib-base=3.8.0=py311h3bc9839_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdit-py-plugins=0.4.0=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - minizip=4.0.1=h5a7aac7_4
  - mistune=3.0.1=pyhd8ed1ab_0
  - monotonic=1.5=py_0
  - movingpandas=0.17.1=pyhd8ed1ab_0
  - msgpack-python=1.0.6=py311he4fd1f5_0
  - multipledispatch=0.6.0=py_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.8.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.8.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h7ea286d_0
  - neptune=1.8.2=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.6.4=nompi_py311hbb54521_103
  - nettle=3.8.1=h63371fa_1
  - networkx=3.1=pyhd8ed1ab_0
  - notebook=7.0.4=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=hb7217d7_0
  - nss=3.92=hc6b9969_0
  - numba=0.57.1=py311hbf3c4e2_0
  - numpy=1.24.4=py311hb8f3215_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - opencv=4.8.1=py311ha1ab1f8_0
  - openh264=2.3.1=hb7217d7_2
  - openjpeg=2.5.0=h4c1507b_3
  - openssl=3.1.4=h0d3ecfb_0
  - orc=1.9.0=hbfdecac_2
  - overrides=7.4.0=pyhd8ed1ab_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.1=py311h9e438b8_1
  - pandoc=3.1.3=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.2.3=pyhd8ed1ab_0
  - param=1.13.0=pyh1a96a4e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py311he9c13d2_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.42.2=h13dd4ca_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - poppler=23.08.0=h7fbffb0_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.0=h00cd704_1
  - proj=9.3.0=h4b7dc33_1
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311heffc1b2_1
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.13=h13dd4ca_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.8.1=py311hf3b2ce4_0
  - pyarrow=13.0.0=py311hd7bc329_4_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyobjc-core=10.0=py311hb702dc4_0
  - pyobjc-framework-cocoa=10.0=py311hb702dc4_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.6.1=py311he1f72a7_2
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.5=h47c9636_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyviz_comms=3.0.0=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311heffc1b2_1
  - pyzmq=25.1.1=py311hb1af645_1
  - re2=2023.03.02=hc5e2d97_0
  - readline=8.2=h92ec313_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987=1.3.8=py_0
  - rpds-py=0.10.3=py311h0563b04_1
  - rtree=1.0.1=py311hd698ff7_3
  - s3transfer=0.7.0=pyhd8ed1ab_0
  - scikit-learn=1.3.1=py311hf0b18b8_0
  - scipy=1.11.3=py311h93d07a4_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shapely=2.0.1=py311h7089352_3
  - simplejson=3.19.2=py311h05b510d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.43.0=h203b68d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.7.0=hb765f3a_0
  - swagger-spec-validator=3.0.3=pyhd8ed1ab_0
  - tbb=2021.10.0=h1995070_1
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.16.3=he15c4da_3
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=hb31c410_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py311heffc1b2_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.10.1=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzcode=2023c=h1a8c8d9_0
  - tzdata=2023c=h71feb2d_0
  - uc-micro-py=1.0.1=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.18=pyhd8ed1ab_0
  - wcwidth=0.2.7=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.3=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xarray=2023.9.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=hd886eac_3
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2023.7.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - intervaltree==3.1.0
      - jupyter-dashboards==0.7.0
      - pathpy3==3.1.1
      - singledispatchmethod==1.0
      - sortedcontainers==2.4.0
prefix: /Users/janhendrikwebert/miniforge3/envs/env_geo
